name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  codestyle:
    name: "Code style & sanity checks"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: "Install Poetry"
      # The newer `install-poetry.py` is bugged: https://github.com/python-poetry/poetry/issues/3870
      run: curl --silent --show-error https://raw.githubusercontent.com/python-poetry/poetry/7360b09e4ba3c01e1d5dc6eaaf34cb3ff57bc16e/get-poetry.py | python - --no-modify-path
      env:
        POETRY_VERSION: 1.1.6
    - name: Install dependencies
      run: ~/.poetry/bin/poetry install --no-root
    - name: Run sanity check
      run: _misc/check_sanity.py
    - name: Run license headers check
      run: _misc/ensure_license_headers.py -s shuup
    - name: Check flake8
      run: ~/.poetry/bin/poetry run flake8 .
    - name: Check isort
      run: ~/.poetry/bin/poetry run isort --check --diff .
    - name: Check black
      run: ~/.poetry/bin/poetry run black --check --diff .

  core:
    name: "Test Shuup, migrations and messages"
    runs-on: ubuntu-latest
    env:
      SHUUP_BROWSER_TESTS: 0
      SHUUP_TESTS_CI: 1
    strategy:
      matrix:

        include:
          - python-version: "3.6"
            django-version: "Django>=2,<3"
          - python-version: "3.7"
            django-version: "Django>=3,<4"
          - python-version: "3.8"
            django-version: "Django>=3,<4"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: "Install Poetry"
      # The newer `install-poetry.py` is bugged: https://github.com/python-poetry/poetry/issues/3870
      run: curl --silent --show-error https://raw.githubusercontent.com/python-poetry/poetry/7360b09e4ba3c01e1d5dc6eaaf34cb3ff57bc16e/get-poetry.py | python - --no-modify-path
      env:
        POETRY_VERSION: 1.1.6
    - name: Install gettext
      run: sudo apt-get -y install gettext
    - name: Install dependencies
      run: |
        ~/.poetry/bin/poetry install --no-root
        pip install -e .

    - name: Install Django
      run: pip install $DJANGO_VERSION
      env:
        DJANGO_VERSION: ${{ matrix.django-version }}
    - name: Run migrations
      run: python -m shuup_workbench migrate
    - name: Run makemessages
      run: python -m shuup_workbench shuup_makemessages -l en
    - name: Run tests
      run: ~/.poetry/bin/poetry run py.test --nomigrations shuup_tests --cov shuup --cov-config=.coveragerc
    - name: Run compilemessages
      run: python -m shuup_workbench compilemessages
    - name: Run code coverage
      run: ~/.poetry/bin/poetry run codecov

  # browser:
  #   name: "Test Shuup with browser"
  #   runs-on: ubuntu-latest
  #   env:
  #     SHUUP_BROWSER_TESTS: 1
  #     SHUUP_TESTS_CI: 1
  #     SHUUP_WORKBENCH_DISABLE_MIGRATIONS: 1
  #   strategy:
  #     matrix:
  #       python-version: ['3.6']
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python
  #     uses: actions/setup-python@v1
  #     with:
  #       python-version: ${{ matrix.python-version }}
  #   - name: Setup Chrome Driver
  #     uses: nanasess/setup-chromedriver@master
  #   - name: Install gettext
  #     run: sudo apt-get -y install gettext
  #   - name: Build static files
  #     run: python setup.py build_resources
  #   - name: Install test dependencies
  #     run: pip install -r requirements-tests.txt
  #   - name: Build messages
  #     run: python setup.py build_messages
  #   - name: Set env
  #     run: echo "DISPLAY=:99.0" >> $GITHUB_ENV
  #   - name: Run tests
  #     run: py.test -v --nomigrations shuup_tests/browser/ --splinter-webdriver=chrome --splinter-screenshot-dir=.browser_tests/
  #   - uses: actions/upload-artifact@v2
  #     if: failure()
  #     with:
  #       name: browser_tests
  #       path: .browser_tests/*.*
